// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pppk.WebApi;

#nullable disable

namespace Pppk.WebApi.Migrations
{
    [DbContext(typeof(HealthcareContext))]
    [Migration("20260812130917_AddSpecialtyExaminationTypeSeed")]
    partial class AddSpecialtyExaminationTypeSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pppk.WebApi.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("house_number");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("address");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.AddressType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("address_type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Boravište"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Prebivalište"
                        });
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<int>("ExaminationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("examination_type_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationTypeId");

                    b.HasIndex("DoctorId", "ScheduledAt")
                        .IsUnique();

                    b.HasIndex("PatientId", "ScheduledAt")
                        .IsUnique();

                    b.ToTable("appointment");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("condition");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hipertenzija"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dijabetes tipa 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Astma"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Migrena"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fibrilacija atrija"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ekcem"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gastritis"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hipotireoza"
                        });
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer")
                        .HasColumnName("specialty_id");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("doctor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ana",
                            LastName = "Kovač",
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Marko",
                            LastName = "Horvat",
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Ivana",
                            LastName = "Novak",
                            SpecialtyId = 3
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Petar",
                            LastName = "Marić",
                            SpecialtyId = 4
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Lucija",
                            LastName = "Jurić",
                            SpecialtyId = 5
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Tomislav",
                            LastName = "Babić",
                            SpecialtyId = 6
                        });
                });

            modelBuilder.Entity("Pppk.WebApi.Models.ExaminationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("examination_type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CT",
                            Name = "Kompjuterizirana tomografija"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MR",
                            Name = "Magnetska rezonanca"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ULTRA",
                            Name = "Ultrazvuk"
                        },
                        new
                        {
                            Id = 4,
                            Code = "EKG",
                            Name = "Elektrokardiogram"
                        },
                        new
                        {
                            Id = 5,
                            Code = "ECHO",
                            Name = "Ehokardiogram"
                        },
                        new
                        {
                            Id = 6,
                            Code = "OKO",
                            Name = "Pregled oka"
                        },
                        new
                        {
                            Id = 7,
                            Code = "DERM",
                            Name = "Dermatološki pregled"
                        },
                        new
                        {
                            Id = 8,
                            Code = "DENTA",
                            Name = "Stomatološki pregled"
                        },
                        new
                        {
                            Id = 9,
                            Code = "MAMMO",
                            Name = "Mamografija"
                        },
                        new
                        {
                            Id = 10,
                            Code = "EEG",
                            Name = "Elektroencefalogram"
                        });
                });

            modelBuilder.Entity("Pppk.WebApi.Models.MedicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("condition_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("PatientId", "ConditionId", "StartDate")
                        .IsUnique();

                    b.ToTable("medical_history");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("medication");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lisinopril"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Metformin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Salbutamol"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sumatriptan"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bisoprolol"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hidrokortizon"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Omeprazol"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Levotiroksin"
                        });
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Oib")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("oib");

                    b.HasKey("Id");

                    b.HasIndex("Oib")
                        .IsUnique();

                    b.ToTable("patient");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.PatientAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<int>("AddressTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("address_type_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("AddressTypeId");

                    b.HasIndex("PatientId", "AddressTypeId")
                        .IsUnique();

                    b.ToTable("patient_address");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("postal_code");

                    b.HasKey("Id");

                    b.HasIndex("PostalCode")
                        .IsUnique();

                    b.ToTable("post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Zagreb",
                            PostalCode = "10000"
                        },
                        new
                        {
                            Id = 2,
                            City = "Split",
                            PostalCode = "21000"
                        },
                        new
                        {
                            Id = 3,
                            City = "Rijeka",
                            PostalCode = "51000"
                        },
                        new
                        {
                            Id = 4,
                            City = "Osijek",
                            PostalCode = "31000"
                        },
                        new
                        {
                            Id = 5,
                            City = "Zadar",
                            PostalCode = "23000"
                        },
                        new
                        {
                            Id = 6,
                            City = "Sesvete",
                            PostalCode = "10360"
                        });
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("condition_id");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dosage");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frequency");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer")
                        .HasColumnName("medication_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PatientId", "MedicationId", "ConditionId")
                        .IsUnique();

                    b.ToTable("prescription");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("specialty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Radiologija"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kardiologija"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Oftalmologija"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dermatologija"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dentalna medicina"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Neurologija"
                        });
                });

            modelBuilder.Entity("Pppk.WebApi.Models.SpecialtyExaminationType", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer")
                        .HasColumnName("specialty_id");

                    b.Property<int>("ExaminationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("examination_type_id");

                    b.HasKey("SpecialtyId", "ExaminationTypeId");

                    b.HasIndex("ExaminationTypeId");

                    b.ToTable("specialty_examination_type");

                    b.HasData(
                        new
                        {
                            SpecialtyId = 1,
                            ExaminationTypeId = 1
                        },
                        new
                        {
                            SpecialtyId = 1,
                            ExaminationTypeId = 2
                        },
                        new
                        {
                            SpecialtyId = 1,
                            ExaminationTypeId = 3
                        },
                        new
                        {
                            SpecialtyId = 1,
                            ExaminationTypeId = 9
                        },
                        new
                        {
                            SpecialtyId = 2,
                            ExaminationTypeId = 4
                        },
                        new
                        {
                            SpecialtyId = 2,
                            ExaminationTypeId = 5
                        },
                        new
                        {
                            SpecialtyId = 3,
                            ExaminationTypeId = 6
                        },
                        new
                        {
                            SpecialtyId = 4,
                            ExaminationTypeId = 7
                        },
                        new
                        {
                            SpecialtyId = 5,
                            ExaminationTypeId = 8
                        },
                        new
                        {
                            SpecialtyId = 6,
                            ExaminationTypeId = 10
                        });
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Address", b =>
                {
                    b.HasOne("Pppk.WebApi.Models.Post", "Post")
                        .WithMany("Addresses")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Appointment", b =>
                {
                    b.HasOne("Pppk.WebApi.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pppk.WebApi.Models.ExaminationType", "ExaminationType")
                        .WithMany("Appointments")
                        .HasForeignKey("ExaminationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pppk.WebApi.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("ExaminationType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Doctor", b =>
                {
                    b.HasOne("Pppk.WebApi.Models.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.MedicalHistory", b =>
                {
                    b.HasOne("Pppk.WebApi.Models.Condition", "Condition")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pppk.WebApi.Models.Patient", "Patient")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.PatientAddress", b =>
                {
                    b.HasOne("Pppk.WebApi.Models.Address", "Address")
                        .WithMany("PatientAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pppk.WebApi.Models.AddressType", "AddressType")
                        .WithMany("PatientAddresses")
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pppk.WebApi.Models.Patient", "Patient")
                        .WithMany("PatientAddresses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("AddressType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Prescription", b =>
                {
                    b.HasOne("Pppk.WebApi.Models.Condition", "Condition")
                        .WithMany("Prescriptions")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pppk.WebApi.Models.Medication", "Medication")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pppk.WebApi.Models.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Medication");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.SpecialtyExaminationType", b =>
                {
                    b.HasOne("Pppk.WebApi.Models.ExaminationType", "ExaminationType")
                        .WithMany("SpecialtyExaminationTypes")
                        .HasForeignKey("ExaminationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pppk.WebApi.Models.Specialty", "Specialty")
                        .WithMany("SpecialtyExaminationTypes")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExaminationType");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Address", b =>
                {
                    b.Navigation("PatientAddresses");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.AddressType", b =>
                {
                    b.Navigation("PatientAddresses");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Condition", b =>
                {
                    b.Navigation("MedicalHistories");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.ExaminationType", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("SpecialtyExaminationTypes");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Medication", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalHistories");

                    b.Navigation("PatientAddresses");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Post", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Pppk.WebApi.Models.Specialty", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("SpecialtyExaminationTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
